### ISSUE TITLE
Migrate to a Mediawiki farm?

### ISSUE THREAD

**Issue by endolith** [electorama/electowiki#4]
How will this be hosted if migrated to Github and Markdown?  I don't know of any Markdown wiki software, especially not with all the Mediawiki features that people are using in articles.

There are a bunch of MediaWiki farms that sound like they do the frustrating stuff for you: https://www.mediawiki.org/wiki/Hosting_services I only looked through a few from that list and already found https://meta.miraheze.org which is free (donations), supports extensions like VisualEditor, custom domain, etc. 

Could it be migrated to one of those?

**Comment by endolith** [comment]
So from the sound of it, we just need the XML dump to migrate to a new host.  I was able to go to https://wiki.electorama.com/wiki/Special:AllPages and manually copypaste all the page names (from all namespaces) into https://wiki.electorama.com/wiki/Special:Export and generate a 36.5 MiB XML file that appears to contain all the revision history.  

I also tried to find copies of all the images, which are mostly broken:

Working:
-    File:Burlington2009election-infosheet.png
-    File:Burlington2009election-infosheet.svg
- File:Tennessee map for voting example.svg

Original still exists on Wikipedia ([Miraheze can include these directly](https://meta.miraheze.org/wiki/FAQ#Why_are_Wikimedia_Commons_files_on_my_wiki.3F)):
- File:Approval ballot.svg
- File:Plurality ballot.svg
- File:Preferential ballot.svg
- File:Tennessee-vote.svg

Found copies on Wayback Machine:
- File:Bsdstyle.png
- File:Chickendilemma.png
- File:CondorcetTennesee.png
- File:Dfc200.gif

Can't find copies of:
- File:Condorcetparadox.png
- File:PAL infographic.png (has multiple versions too)
- File:ElectoWiki-150x91.jpg (unimportant?)
- File:Electowidget-screenshot.jpg (unimportant?)
- File:Electowiki150x93.jpg (unimportant?)
- File:Electowiki3.JPG (unimportant?)
- File:VEorama.png (unimportant?)

As well as made copies of site images:
- electodrop.png
- favicon.ico
- bluetile.png (unimportant)
- right_bkgbrightylw.png (unimportant)

**Comment by endolith** [comment]
Import instructions here: https://meta.miraheze.org/wiki/Moving_a_wiki_to_Miraheze

**Comment by endolith** [comment]
Well.. um...  I went ahead and did it: https://electowiki.miraheze.org/wiki/Main_Page

* Encoding errors have been fixed ([old](https://wiki.electorama.com/wiki/Phragm%C3%83%C6%92%C3%82%C2%A9n%27s_Method) vs [new](https://electowiki.miraheze.org/wiki/Phragm%C3%A9n%27s_Method))
* Some broken images have been resurrected ([some are still missing](https://electowiki.miraheze.org/wiki/Special:AllPages?from=&to=&namespace=6))
* Some other images have been switched to use Wikimedia Commons ([Example](https://electowiki.miraheze.org/wiki/File:Approval_ballot.svg))
* Some spam deleted
* VisualEditor and Graph extensions are enabled
* Math works ([old](http://wiki.electorama.com/wiki/Instant_Runoff_Normalized_Ratings) vs [new](https://electowiki.miraheze.org/wiki/Instant_Runoff_Normalized_Ratings))
* Interwiki links to Wikipedia work
* Interwiki templates work ("scary transclusion") ([Example](https://electowiki.miraheze.org/w/index.php?title=3-2-1_voting&diff=3945&oldid=74))

**Comment by endolith** [comment]
@robla  @jamesonquinn @dkesh

**Comment by robla** [comment]
@endolith - thanks for getting my attention over in the EndFPTP Slack workspace.  The migrated version looks pretty sharp.  Per our conversation, I think we can make the migration via soft redirects on a per-page basis rather than trying to transfer the domain over.  That'll be slower, but it'll make it so that we can undo the migration if we need to, and also give us the opportunity to prune things out of the migration.

I see you've been pretty busy today with imports/etc: 

* https://electowiki.miraheze.org/wiki/Special:Contributions/Psephomancy

Let me know when you feel like the new wiki is ready to be the primary host for pages which are currently hosted at wiki.electorama.com

**Comment by endolith** [comment]
@robla  Yeah the templates are a nightmare.  Everything else has been pretty straightforward, but the templates are a mess of dependencies (other templates, Lua modules, CSS styles).  Anyway it looks like some of them work now:

![image](https://user-images.githubusercontent.com/58611/44951313-6c642b00-ae2f-11e8-84fd-b55340b28f68.png)

The Graph:Chart template is cool:

https://electowiki.miraheze.org/wiki/Talk:Mean_minimum_political_distance



I added little icons after Wikipedia links, to encourage using those for things that don't need a local article:

![image](https://user-images.githubusercontent.com/58611/44951341-f6ac8f00-ae2f-11e8-8bc9-82352977241b.png)

I'm happy to change that if people think it's ugly.  

But I figure "If Wikipedia will accept the content, put it on Wikipedia.  This wiki is for original research (both newly-invented voting methods and analysis of existing ones), advocacy, and content with weak sources that gets rejected/deleted from Wikipedia."

Would this github be the right place to keep track of issues with this wiki?
